config/routes.rb
CMS::Application.routes.draw do
  get "admin/index"

  get "session/new"

  get "session/create"

  get "session/destroy"

  resources :users
get 'admin' => 'admin#index'
controller :sessions do
get 'login' => :new
post 'login' => :create
delete 'logout' => :destroy
end

  get "store/index"

  resources :pages do
    resources :comments
  end

  root :to => 'store#index', :as => 'store'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :page
end

app/models/page.rb
class Page < ActiveRecord::Base
validates :title, :body,:permalink,:created_at,:presence => true
validates :title, :uniqueness => true
default_scope :order => 'title ASC'
#validates :created_at
has_many :comments 
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
def User.authenticate(name, password)
 if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
      user
      end
    end
end
  
  def User.encrypt_password(password, salt)
Digest::SHA2.hexdigest(password + "wibble" + salt)
end

  def password=(password)
 @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
end
  
  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end
   def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_pages = Page.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def create
    
    @page = Page.find(params[:page_id])
    @comment = @page.comments.create(params[:comment])
    # redirect_to page_path(@page)
    respond_to do |format|
      Notifier.comment_recieved(@comment).deliver
      format.html { redirect_to :back}
      format.js
      
    # format.json { render json: @page, status: :created, location: @page }
    #else
    #format.html { render action: "new" }
    #format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        #form.html { redirect_to new_session_path()}
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    create
    
  end

  def create
     if user = User.authenticate(params[:name], params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, :alert => "Invalid user/password combination"
    end
  end

  def destroy
     session[:user_id] = nil
    redirect_to store_url, :notice => "Logged out"
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  @pages = Page.paginate( :page=>params[:page], :order=>'created_at desc', :per_page => 2)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.order(:name)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_url,:notice => "User #{@user.name} was successfully created.") }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url,:notice => "User #{@user.name} was successfully updated.") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_pages, "page") %>.

app/views/comments/_comment.html.erb
<hr/>
<% if comment == @current_comment %>
<p class="list_line_odd">
	<% else %>
	<p>
		<% end %>
    <b>Commenter:</b>
    <%= comment.commenter_name %>
  </p>
 <p>
    <b>Email address:</b>
    <%= comment.email_address %>
  </p>
  <p>
    <b>Comment:</b>
    <%= comment.description%>
  </p>

app/views/comments/_form.html.erb
<%= form_for([@page, @page.comments.build],:remote => true ,:html => { :id => 'comment_form'}) do |f| %>
<div class="field">
	<%= f.label :commenter_name %>
	<br />
	<%= f.text_field :commenter_name %>
</div>
<div class="field">
	<%= f.label :email_address %>
	<br />
	<%= f.text_field :email_address %>
</div>
<div class="field">
	<%= f.label :description %>
	<br />
	<%= f.text_area :description, :rows => 5, :cols => 40 %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commenter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commenter:</b>
  <%= @comment.commenter_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS</title>
  <%= stylesheet_link_tag "styles", :media=>"all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


</head>

<body>
<div id="main">
<div id="content">
<div id="logo">
<div class="logo_r">
<h5>Welcome to Our CMS</h5>
</div>
</div>
<%=@page_title || "Pragmatic BookShelf"%>
<div id="columns">
<div id="left">
<div class="list">
<div class="opt">
        <h1>Menu</h1>
		<div class="opt_a">
        <a href="http://cms-csse-8sem.herokuapp.com "> Home</a><br/>
		</div>
			<div class="opt_a">
			<a href="http://cms-csse-8sem.herokuapp.com/faq">Questions</a><br/>
			</div>
	<div class="opt_a">
			<a href="http://cms-csse-8sem.herokuapp.com/pages/new">News</a><br/>
			</div>
  <div class="opt_a">
  <a href="http://localhost:3000/contact">Contact</a><br/>
    </div>
	</div>
	</div>
	</div>
    
<div id="left">
<div class="list">

</div>
</div>
<div id="right">
<div class="text">
<%= yield %>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html1111.erb
<!DOCTYPE html>
<html>
	<head>
		<title>CMS</title>
		<%= stylesheet_link_tag "application", :media=>"all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body id="store">
		<div id="banner">
			<%= image_tag("logo.png")%>
			<%= @page_title || "Pragmatic BookShelf"%>
		</div>
		<div id="columns">
			<div id="side">
				<a href="<% 'hostname'.strip %>/"> Home</a>
				<br/>
				<a href="<% 'hostname'.strip %>/faq">Questions</a>
				<br/>
				<a href="<% 'hostname'.strip %>/pages/new">New Post</a>
			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/notifier/comment_delivered.text.erb
Notifier#comment_delivered

<%= @greeting %>, find me in app/views/app/views/notifier/comment_delivered.text.erb
Dear <%= @comment.commenter_name %>
Thank you for your recent comment from The KM CMS.
You comment the following items:

We'll send you a separate e-mail when your order ships.

app/views/notifier/comment_recieved.text.erb
Notifier#comment_recieved

Dear <%= @comment.commenter_name %>
Thank you for your recent comment from The KM CMS.
You comment the following items:
<%= @comment.page.title %>


We'll send you a separate e-mail when your order ships.

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
<% if @page.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
	<ul>
		<% @page.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :title %>
	<br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :permalink %>
	<br />
	<%= f.text_field :permalink %>
</div>
<div class="field">
	<%= f.label :body %>
	<br />
	<%= f.text_area :body %>
</div>
<div class="field">
	<%= f.label :created_at %>
	<br />
	<%= f.datetime_select :created_at %>
</div>
<div class="field">
	<%= f.label :updated_at %>
	<br />
	<%= f.datetime_select :updated_at %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %> 

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<div id="page_list" class="divStyle">

<h1>Listing pages</h1>
<hr/>
<table>


<% @pages.each do |page| %>
  <tr class="<%= cycle('list_line_odd','list_line_even') %>">

    <td class="list_description">
<dl>
<dt><%= page.title %></dt>
<dd><%= truncate(strip_tags(page.body), :length =>70) %></dd>
</dl> </td>
    <td><%= page.created_at %></td>
	<td class="list_actions">
    <%= link_to 'Show', page %><br/>
    <%= link_to 'Edit', edit_page_path(page) %><br/>
    <%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %>
<td><hr/></td>

  </tr>
<% end %>
</table>
<hr/>
</div>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
  <script type="text/javascript">
  $('documet').ready(function(){
    $('#form_button').toggle(function(){
      $('#two').slideDown(1000);
	  $('#form_button').html("Hide Form");
    },
	function(){
      $('#two').slideUp(1000);
	  $('#form_button').html("Show Form");
    })
	
  })
   $('documet').ready(function(){
    $('#button').click(function(){
      $('#show_comment').toggle(1000);
    })
  })
  </script>
<p id="notice">
	<%= notice %>
</p>
<div id="page_div">
	<p>
		<b>Title:</b>
		<%= @page.title %>
	</p>
	<p>
		<b>Permalink:</b>
		<%= @page.permalink %>
	</p>
	<p>
		<b>Body:</b>
		<%= @page.body %>
	</p>
	<p>
		<b>Created at:</b>
		<%= @page.created_at %>
	</p>
	<p>
		<b>Updated at:</b>
		<%= @page.updated_at %>
	</p>
</div>
<hr/>
<h1>Comments</h1>
<button id="button">Show Comment</button> <br />
<div id="show_comment" style="display: none">
	<% com=@page.comments.paginate( :page=>params[:page], :per_page => 2)%>
	<%= render com %>
	<%= will_paginate com %>
</div>
<hr/>
<h1> Add a comment: </h1>
<button id="form_button">Show Form</button> <br /><br />
<div id="two" style="background:gray;display:none">
	
	<%= render "comments/form" %>
</div>
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %> 

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

<p>Find me in app/views/session/new.html.erb</p>
<div class="depot_form" >
	<% if flash[:alert] %>
	<p id="notice" >
		<%= flash[:alert] %>
	</p>
	<% end %>
	<%= form_tag do %>
	<fieldset>
		<legend>
			Please Log In
		</legend>
		<div>
			<label for="name" >Name:</label>
			<%= text_field_tag :name, params[:name] %>
		</div>

<div>
			<label for="password" >Password:</label>
			<%= password_field_tag :password, params[:password] %>
		</div>
		<div>
			<%= submit_tag "Login" %>
		</div>
		</fieldset>
		<% end %> </div>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>
<div class="depot_form" >
	<% if flash[:alert] %>
	<p id="notice" >
		<%= flash[:alert] %>
	</p>
	<% end %>
	<%= form_tag do %>
	<fieldset>
		<legend>
			Please Log In
		</legend>
		<div>
			<label for="name" >Name:</label>
			<%= text_field_tag :name, params[:name] %>
		</div>

<div>
			<label for="password" >Password:</label>
			<%= password_field_tag :password, params[:password] %>
		</div>
		<div>
			<%= submit_tag "Login" %>
		</div>
		</fieldset>
		<% end %> </div>

app/views/store/index.html.erb
<% if notice %>
<p id="notice">
	<%= notice%>
</p>
<%end%> <h1> Your Pragmatic Catalog</h1>
<% @pages.each do |page| %>
<div class="entry">
	<div class="text">
	<h3> <%= page.title%></h3>
	<%= sanitize(page.body)%>
</div>
</div>
<%= button_to "Add a comment", page, :method => 'get'%>
<%end%> 
<p><%= will_paginate @pages %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hashed_password %><br />
    <%= f.text_field :hashed_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice" >
	<%= notice %>
</p>
<% end %> 
<table>
  <tr>
    <th>Name</th>
    <th>Hashed password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.hashed_password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>